name: PoolCalGenerator
description: iCal generator for SDU pool schedule
# version: 1.0.0
# homepage: https://www.example.com
# author: Stepan <stmar17@student.sdu.dk>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  dio: ^1.0.6
  spreadsheet_decoder: ^1.0.0
  intl: ^0.15.7
  uuid: ^1.0.3
  cron: ^0.2.1
  date_calendar: ^0.2.0
  HTMLSelecter:
    git: https://github.com/Kioshi/HTMLSelecter.git

dev_dependencies:
  test: ^1.0.0
